import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import worker from '../src/worker.js';

const browser = await chromium.launch({ headless: true });
for (const viewport of [{ width: 1440, height: 900 }, { width: 390, height: 844 }]) {
  const page = await browser.newPage({ viewport });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('https://connect.facebook.net/**', route => route.abort());
  await page.goto('http://127.0.0.1:4173/?utm_source=qa&utm_campaign=quiz');
  assert.equal(await page.locator('[data-apply]').count(), 5);
  for (const cta of await page.locator('[data-apply]').all()) assert.equal(await cta.getAttribute('href'), '#diagnostico');
  await page.locator('[data-apply="hero"]').click();
  const quiz = page.frameLocator('#quiz-frame');
  await quiz.getByLabel('Seu nome', { exact: true }).fill('Maria Silva');
  await page.getByRole('button', { name: 'Voltar à apresentação' }).click();
  await page.locator('[data-apply="final"]').click();
  assert.equal(await quiz.getByLabel('Seu nome', { exact: true }).inputValue(), 'Maria Silva');
  await quiz.getByRole('button', { name: 'Começar análise' }).click();
  await quiz.getByRole('button', { name: 'Outro modelo de negócio', exact: true }).click();
  assert(await quiz.getByRole('button', { name: 'Continuar', exact: true }).isDisabled());
  await quiz.getByRole('button', { name: 'Distribuidora', exact: true }).click();
  await quiz.getByRole('button', { name: 'Continuar', exact: true }).click();
  await quiz.getByRole('button', { name: 'Acima de R$1 milhão/mês', exact: true }).click();
  await quiz.getByRole('button', { name: 'Continuar', exact: true }).click();
  await quiz.getByRole('button', { name: 'Prospecção ativa', exact: true }).click();
  await quiz.getByRole('button', { name: 'Continuar', exact: true }).click();
  await quiz.getByRole('button', { name: 'Ver meu diagnóstico' }).click();
  await quiz.getByText('Informe o nome da empresa.', { exact: true }).waitFor();
  await quiz.getByLabel('Nome da empresa *', { exact: true }).fill('Empresa Teste');
  await quiz.getByLabel('WhatsApp *', { exact: true }).fill('11999999999');
  await quiz.getByLabel('E-mail *', { exact: true }).fill('qa@example.com');
  await quiz.getByRole('checkbox').check();
  let payload;
  let releaseDelivery;
  const deliveryGate = new Promise(resolve => { releaseDelivery = resolve; });
  await page.route('**/api/submit', async route => {
    payload = route.request().postDataJSON();
    await deliveryGate;
    await route.fulfill({ status: 502, json: { success: false } });
  });
  await quiz.getByRole('button', { name: 'Ver meu diagnóstico' }).click();
  await quiz.getByRole('heading', { name: 'Maria, sua empresa tem uma Operação com Potencial' }).waitFor();
  assert(await quiz.getByRole('button', { name: 'Enviando dados…' }).isDisabled());
  releaseDelivery();
  await quiz.getByText('Seu diagnóstico está pronto, mas seus dados ainda não foram enviados', { exact: false }).waitFor();
  assert.equal(await quiz.getByText('Recebemos seus dados.', { exact: false }).count(), 0);
  assert.equal(await page.evaluate(() => window.dataLayer.filter(item => item.event === 'quiz_complete').length), 0);
  const failedPayload = payload;
  await page.unroute('**/api/submit');
  await page.route('**/api/submit', async route => {
    payload = route.request().postDataJSON();
    await route.fulfill({ json: { success: true } });
  });
  await quiz.getByRole('button', { name: 'Tentar enviar novamente' }).click();
  await quiz.getByText('Recebemos seus dados.', { exact: false }).waitFor();
  assert.deepEqual(payload, failedPayload);
  await quiz.getByRole('heading', { name: 'Maria, sua empresa tem uma Operação com Potencial' }).waitFor();
  assert.equal(payload.utm_source, 'qa');
  assert.equal(payload.utm_campaign, 'quiz');
  assert.equal(payload.tipo_operacao, 'Distribuidora');
  assert(payload.url_pagina.includes('/?utm_source=qa'));
  assert.equal(new URL(page.url()).pathname, '/');
  assert.deepEqual(errors, []);
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  const frame = page.frames().find(frame => frame.url().includes('/quiz/'));
  assert(await frame.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: `.sites-runtime/quiz-${viewport.width}.png` });
  const events = await page.evaluate(() => window.dataLayer.map(item => item.event));
  assert.equal(events.filter(event => event === 'quiz_start').length, 1);
  assert.equal(events.filter(event => event === 'quiz_complete').length, 1);
  await page.goBack();
  assert.equal(await page.locator('#diagnostico').evaluate(el => el.open), false);
  await page.close();
  console.log(`Quiz OK: ${viewport.width}px; validação, voltar, envio simulado, erro, UTMs e resultado.`);
}
await browser.close();
const originalFetch = globalThis.fetch;
const sample = { nome_completo: 'Maria Silva', empresa: 'Empresa Teste', whatsapp_limpo: '11999999999', email: 'qa@example.com', privacy_consent: true, utm_source: 'qa' };
const request = body => new Request('https://site.test/api/submit', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: 'https://site.test' }, body: JSON.stringify(body) });
globalThis.fetch = async (_url, options) => { assert.equal(JSON.parse(options.body).phone, sample.whatsapp_limpo); return new Response('{}', { status: 200 }); };
assert.equal((await worker.fetch(request(sample), {})).status, 200);
assert.equal((await worker.fetch(request({}), {})).status, 400);
globalThis.fetch = async () => new Response('', { status: 402 });
assert.equal((await worker.fetch(request(sample), {})).status, 502);
globalThis.fetch = originalFetch;
console.log('API OK: mapeamento CRM, validação e falha do serviço. Nenhum cadastro real enviado.');
